name: radioplenitudesvie
description: La Vie de Christ dans toutes Ses PlÃ©nitudeS au travers des ondes.
publish_to: 'none'

version: 1.0.14+15

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get_it: ^7.2.0 
  rxdart: '>=0.26.0 <0.28.0'
  in_app_update: ^4.2.2
  flutter_spinkit: ^5.2.0
  story_view: ^0.15.0
  get: ^4.6.6
  sqflite: ^2.3.0
  flutter_widget_from_html: ^0.14.6 
  animated_bottom_navigation_bar: ^1.3.0
  bottom_navy_bar: ^6.0.0
  package_info_plus: ^4.2.0
  animations: ^2.0.0
  url_launcher: ^6.1.14
  audioplayers: ^5.2.0
  text_scroll: ^0.2.0
  lottie: ^2.7.0
  skeletonizer: ^0.8.0
  audio_session: ^0.1.18
  audio_service: ^0.18.12
  permission_handler: ^11.0.1
  image_gallery_saver: ^2.0.3
  share_plus: ^7.2.1
  calendar_appbar: ^0.0.6
  youtube_api: ^1.0.4
  just_audio_background: ^0.0.1-beta.11
  cached_network_image: ^3.3.0
  youtube_player_flutter: ^8.1.2
  radio_player: ^1.5.0
  carousel_slider: ^4.2.1
  path_provider: ^2.1.1
  unorm_dart: ^0.2.0
  path: ^1.8.3
  intl: ^0.17.0
  simple_month_year_picker: ^1.0.5
  mat_month_picker_dialog: ^1.1.1
  google_fonts: ^4.0.4
dev_dependencies:
  flutter_lints: any
  flutter_test:
    sdk: flutter

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/bible.db